### ISSUE TITLE
Preload avatars?

### ISSUE THREAD

**Issue by jason2002131** [gompocp/WorldPredownload#1]
it will be very helpful for people who don't have good internet or don't want to get into an avatar and wait.

**Comment by gompocp** [comment]
Apologies, I didn't see this for a while. I'll consider this for another mod although I'm not sure how you'd want it to function. Do you want to be able to select an avatar and hit a button on the side to download in the background?

**Comment by fwenny** [comment]
selecting an avatar in the Avatar page begins a background download, and when you see the preview it means it finished downloading.
apologies if you meant something else.

**Comment by gompocp** [comment]
Slaynash may have something up his sleeves for this ;) , therefore I'm going to close this issue as it won't be implemented into this mod.
