### ISSUE TITLE
Buttons are not showing up!

### ISSUE THREAD

**Issue by RaspberryKitty1** [gompocp/WorldPredownload#2]
the latest vrchat update broke this mod.
here is the error from the console.
```[17:54:46.962] [WorldPredownload] [ERROR] System.TypeLoadException: Could not resolve type with token 01000029 (from typeref, class/assembly UiUserList, Assembly-CSharp, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null)

  at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 

  at WorldPredownload.SocialMenuPatch.Setup () [0x00014] in <1a94c2bc8dea4fadacb5fe4ce8e59f09>:0 

  at WorldPredownload.WorldPredownload.OnApplicationStart () [0x0001a] in <1a94c2bc8dea4fadacb5fe4ce8e59f09>:0 

  at MelonLoader.MelonHandler.OnApplicationStart_Mods () [0x00023] in <61bd2bb7fbe24a28bc977e05ef482f41>:0 ```

**Comment by gompocp** [comment]
Can you try this version for me: [https://github.com/gompocp/WorldPredownload/releases/download/v1.3.8/WorldPredownload.dll](url) and let me know if the issue persists. Also are you using SteamVR or the Oculus App?

**Comment by RaspberryKitty1** [comment]
I am using nether I am on desktop mode and I am using v. 1.3. 8 every time I boot vrc I get that error the settings load in the ui extension mod but nothing loads in the vrc menu or in invites or world menus like it did before the newist vrc update.  (build 1069)

**Comment by gompocp** [comment]
Cannot reproduce. The only other reason I can think of why this might failing is if your installation of MelonLoader is outdated. So try reinstall firstly, if you still have no luck, you can send your log file here or you can dm me it on discord at gompo#6956 (the latest log file will be at the path VRChat\MelonLoader\Latest.log)

**Comment by RaspberryKitty1** [comment]
[Latest.log](https://github.com/gompocp/WorldPredownload/files/6254249/Latest.log)
i took out all my other mods to narrow it down still errors out here's the log file
melonloader is 0.3.0

**Comment by gompocp** [comment]
Looking at your log file it looks like you have a slightly outdated version of Melonloader v0.3.0. Several hotfixes were released but the version of Melonloader itself wasn't changed. Reinstall using the Official Melonloader Installer and make sure when you launch your game at the very start of your log/console it says `Hash Code: 25916` as yours currently says `Hash Code: 25857`

**Comment by RaspberryKitty1** [comment]
Thanks that worked :) did not realize Ml was out of date

**Comment by gompocp** [comment]
No worries :)
